### PR TITLE
Comprehensive Refactor of To-Do List Application with Enhanced Features

### PR DESCRIPTION
**Pull request by mgiannopoulos24**
### Description:
This pull request introduces extensive updates to the To-Do List application, integrating new features and improvements while maintaining a single file structure. The changes encompass:

1. **Recurring Tasks:**
    - Added functionality to handle recurring tasks with options for daily, weekly, and no recurrence.
    - Updated task management to support recurrence adjustments.
2. **Undo/Redo Feature:**
    - Implemented undo and redo capabilities for reverting and reapplying changes.
    - Utilized stacks to manage undo and redo operations.
3. **Multi-User Support:**
    - Enabled multi-user functionality by allowing user-specific task files.
    - Users log in to manage their own separate task lists.
4. **Backup and Restore Functionality:**
    - Added backup and restore options to safeguard against data loss.
    - Implemented file operations to create backups and restore tasks from backup files.
5. **Advanced Filtering and Sorting:**
    - Introduced advanced filtering options based on status, deadline, priority, and recurrence.
    - Enabled sorting tasks by creation date, deadline, and priority.
 6. **Error Handling and Validation:**
    - Improved error handling for file operations and user inputs.
    - Added validation functions for date, priority, and recurrence inputs.

### Summary of Changes
- **Recurring Tasks:** Enhanced task functionality to handle daily and weekly recurrences.
- **Undo/Redo Feature:** Implemented undo and redo operations for task changes.
- **Multi-User Support:** Added user login to manage separate task lists.
- **Backup/Restore:** Included options to back up and restore tasks.
- **Advanced Filtering/Sorting:** Provided capabilities to filter and sort tasks.
- **Error Handling/Validation:** Improved handling of errors and validation.

### Code Changes
- Implemented functions for recurring tasks, undo/redo, multi-user support, backup/restore, and filtering/sorting.
- Enhanced error handling and validation for user inputs and file operations.
- Maintained a single-file structure to simplify integration.

### Testing Instructions
1. **Manual Testing:**
- Run the script and test each feature, including recurring tasks, undo/redo, multi-user support, backup/restore, and filtering/sorting.
- Verify that user login correctly manages separate task files and that tasks are appropriately backed up and restored.
2. **Validation:**
- Ensure that all validation checks for inputs are functioning correctly.
- Confirm that error messages are displayed for invalid inputs and file operations.
### Notes
- Ensure that dependencies are installed and up-to-date.
- Review the updated functionalities and validate that they perform as expected.
- Consider future modularization for the project, since its above 400 lines of code already.

### CODE REVIEW

**Comment by Vadkon07** [comment]
Oh my god, really nice work! For now it looks much more than just a to-do list hahaha

**Comment by Vadkon07** [comment]
Hm, it was a really nice pull. For now I think we have to edit README for a little, and probably add ClearScreen() for every moment when app prints something new. I tried this app and found her pretty overloaded with text for my mind. To-Do List should be more readable, because for productivity you need better focus and try to keep your had clean from not useful things. For now I will try to do it all.

**Comment by mgiannopoulos24** [comment]
Since you want to add GUI in the future you dont have to worry how it looks on a terminal. GUI's are more compact.

**Comment by Vadkon07** [comment]
Maybe. My laptop is for a little (AMD E300 1.3 Ghz) slow, so I have some problems with GUI development. I think that in the future I will buy a better laptop (I started to save, goal is 200$) and he will open these "doors" to GUI development for me))) So, for now this app is terminal-only

**Pull request merged**
